### ISSUE TITLE
play nicely with dialyxir?

### ISSUE THREAD

**Issue by RichMorin** [Comcast/dialyzex#17]
I've been using Dialyxir intensively for a while, but I'd like to give Dialyzex a try. Sadly, when I try to add them both as dependencies, all sorts of breakage ensue. Please try to find a way to let users install and use both of these packages. (See also: https://github.com/jeremyjh/dialyxir/issues/348)

**Comment by seancribbs** [comment]
Is the problem simultaneously installing both, or that your dependencies rely on more than one without declaring them to be optional or dev-mode only? It feels like you would want to choose one of the two libraries for your own project and stick with it.
